package io.legado.app.domain.model.settings

data class OtherSettings(
    val updateToVariant: String = "official_version",
    val autoCheckUpdateOnStart: Boolean = false,
    val webServiceAutoStart: Boolean = false,
    val autoRefresh: Boolean = false,
    val defaultToRead: Boolean = false,
    val notificationsPost: Boolean = true,
    val ignoreBatteryPermission: Boolean = true,
    val firebaseEnable: Boolean = true,
    val defaultBookTreeUri: String? = null,
    val antiAlias: Boolean = false,
    val replaceEnableDefault: Boolean = true,
    val autoClearExpired: Boolean = true,
    val showAddToShelfAlert: Boolean = true,
    /** 非在架书籍详情页命中确定的在架同作品时，自动触发「在架」行为（单本跳转 / 多本弹窗）。 */
    val autoJumpToShelfBook: Boolean = false,
    val showMangaUi: Boolean = true,
    val webServiceWakeLock: Boolean = false,
    val sourceEditMaxLine: Int = Int.MAX_VALUE,
    val webPort: Int = 1122,
    val processText: Boolean = true,
    val recordLog: Boolean = false,
    val recordHeapDump: Boolean = false,
    val audioPlayUseWakeLock: Boolean = false,
    val importKeepName: Boolean = false,
    val importKeepGroup: Boolean = false,
    val importKeepEnable: Boolean = false,
    val fontSort: Int = 0,
)
